### ISSUE TITLE
Visualization: setting up gulp

### ISSUE THREAD

**Issue by nicola** [densekernel/3001#12]
This could be deprecated

**Comment by himerzi** [comment]
@nicola Can we get rid of this, and just add an issue for setting up X once the visualisation team has decided what X is?

**Comment by nicola** [comment]
Feel free to get rid of this. In my mind this should have been the place to discuss whether we will be using gulp or not

**Comment by himerzi** [comment]
Ok.
What will you be working on?

**Comment by nicola** [comment]
You mean in general? If you mean in general let's not pollute this thread, send me a PM.

On this particular issue I could work an the automation tools for development aka the gulpfile.js that will help reload/compile/do all things, if this level of complexity is needed.
