### ISSUE TITLE
What data exactly are we using, and what are we doing with it?

### ISSUE THREAD

**Issue by himerzi** [densekernel/3001#16]
So, before anything can move forward in a significant way, this question needs to be addressed. I spent a good deal of time on this today, and have some suggestions regarding what variables exactly we'll be measuring, and where we can get the pertinent data.

I suggest that we alter our stated title slightly by replacing "planned engineering works" with "significant public transport delays"  (and how they affect activity at nearby cycle docks). The title would become "Optimisation of TFL Barclays Cycle Hire bicycle distribution during significant public transport delays”
I see "significant public transportation delays" as being in the same spirit of our original title, so this shouldn't be a big issue. The important difference here is that there appears to be and specific data for this, whereas "planned engineering works" offers less data points, and is vaguely defined (as Jonny and other people have noted). See below for what I mean about having good specific data.

After having a look at what's available, it seems we should be able to get values for average time between trains, as well as current time between trains. A large discrepancy between the two would be of interest to us, as we'd be investingating whether or not this affects activity at nearby cycle docks. This data is available by platform and by station. There appears to be [historical data available as well](https://developer.transportapi.com/documentation/tube-information).
- On a map we can mark the stations experiencing train delays, while highlighting nearby cycle docks, and indicating whether that dock is experiencing elevated bike withdrawals (as compared to average). This should be decided in order for #8 to move forward..
- One example of the train data in use is [here](http://tube-radar.com/)
- There is also interesting data for buses. We have timetabled arrival times, as well as "expected" arrival times. For bus stops experiencing a large difference in expected vs timetabled arrival, we should highlight (on our map visualisation) nearby cycle docks, and again, mark the ones experiencing higher-than-average bike withdrawals (again, this should be decided on for #8). 
  - The relevant data is available [here](https://developer.transportapi.com/documentation/bus-information) (see "live bus departures")
  - Here is a live example of [timetabled](https://transportapi.com/v3/uk/bus/stop/490012745J/2014-10-18/17:28/timetable.html?api_key=d9307fd91b0247c607e098d5effedc97&app_id=03bf8009) vs [expected departure](https://transportapi.com/v3/uk/bus/stop/490012745J/live.html?&api_key=d9307fd91b0247c607e098d5effedc97&app_id=03bf8009)  

You'll notice that I've been linking to an api called "transportapi.com" (i.e. not the official tlf api). In the case of tube trains, this api allready has data on average times between trains. Otherwise, we'd have to calculate this ourselves, by collecting a time-series of tfl api data and deriving the average times between trains for different platforms/stations. 

In the case of buses, if we use the tfl feed we'd have to combine the data for bus timetables from the "journey planner timetable" api together with the Live bus and river bus arrivals API http://www.tfl.gov.uk/cdn/static/cms/documents/trackernet-data-services-guide-beta.pdf.

For bikes, everything we need is in "Barclays Cycle Hire availability" feed. We'll mostly use a time series of bike withdrawals, I imagine.

Whoever is in charge of #2 (@navidhg ?) needs to look carefully at all of the different data providers, and data feeds I've listed here, and decide which ones we need to start recording and building a repository of (particularly if we choose to use tfl api directly, and not transportapi.com)
.
We could do either busses only, tubes only, or both. I think we should pick one. So maybe the tittle should actually be: Optimisation of TFL Barclays Cycle Hire bicycle distribution during significant ("bus" || "train") transport delays 

Thoughts? - I think this should be agreed and finalised at the next meeting.

**Comment by nicola** [comment]
I will have a greater answer than this soon. This is blocking for the project as a whole, but not a dependency on the other issues for our friday milestone, that is a very generic structure for what we will be doing. Thanks a lot for this reflection, brb

**Comment by isaacyyy** [comment]
perhaps we should combine the two, planned engineering works and delays?

**Comment by SnubbleJr** [comment]
I think we should remove the name 'Barclays' and turn it just into 'Cycle Hire' from the title, as Barclays aren't actively involved in this scheme anymore; Jonny said that Wonga are taking over.

**Comment by xalodni** [comment]
[edit] nvm

**Comment by ghost** [comment]
Data found
