### ISSUE TITLE
Scrape tube status history

### ISSUE THREAD

**Issue by xalodni** [densekernel/3001#28]
From http://tubestatus.net/timeline/date/2012-08-15

Table could easily be scraped using Beautiful Soup.

Result is a way to determine status given day, line and hour. Going to make a local MySQL table for this.
Visualisation team might want a look.

Will produce record of how I went about scraping it.

Everybody OK with the format of day x line x hour -> status?

**Comment by densekernel** [comment]
Hi Ran, just wondered how this is going along, I would like to analyse this data for some basic stats about the engineering works

**Comment by xalodni** [comment]
http://tubestatus.net/timeline - Can't get anything except the last 24 hours. I won't be able to do anything until I can get timetables by date.

[edit]

Actually I can except it's slow. It's slower than getting the last 24 hours.

**Comment by xalodni** [comment]
Actually I can except it's slow. It's slower than getting the last 24 hours.

**Comment by xalodni** [comment]
Sent an email to the address at the bottom of the website.

**Comment by nicola** [comment]
Scraper #29

**Comment by nicola** [comment]
https://github.com/jonnymanf/3001/tree/master/data
cc @RagavanGun  @mohandai 
Closed 2c664886ad27255a56f3eb7a373c6d8725c2b1a5
